app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

app_ens_profit:
    resource: "@AppBundle/Resources/config/routing/profit.yml"
    prefix:   /profit

app_ens_image:
    resource: "@AppBundle/Resources/config/routing/image.yml"
    prefix:   /image

app_ens_equipment:
    resource: "@AppBundle/Resources/config/routing/equipment.yml"
    prefix:   /equipment

app_ens_deliverable:
    resource: "@AppBundle/Resources/config/routing/deliverable.yml"
    prefix:   /deliverable

app_ens_constraint:
    resource: "@AppBundle/Resources/config/routing/constraint.yml"
    prefix:   /constraint

app_ens_actor:
    resource: "@AppBundle/Resources/config/routing/actor.yml"
    prefix:   /actor

app_ens_action_responsible:
    resource: "@AppBundle/Resources/config/routing/actionresponsible.yml"
    prefix:   /action_responsible

app_ens_action:
    resource: "@AppBundle/Resources/config/routing/action.yml"
    prefix:   /action

app_ens_scenario:
    resource: "@AppBundle/Resources/config/routing/scenario.yml"
    prefix:   /scenario

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media