app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_ens_profit:
    resource: "@AppBundle/Resources/config/routing/profit.yml"
    prefix:   /profit

app_ens_image:
    resource: "@AppBundle/Resources/config/routing/image.yml"
    prefix:   /image

app_ens_equipment:
    resource: "@AppBundle/Resources/config/routing/equipment.yml"
    prefix:   /equipment

app_ens_deliverable:
    resource: "@AppBundle/Resources/config/routing/deliverable.yml"
    prefix:   /deliverable

app_ens_constraint:
    resource: "@AppBundle/Resources/config/routing/constraint.yml"
    prefix:   /constraint

app_ens_actor:
    resource: "@AppBundle/Resources/config/routing/actor.yml"
    prefix:   /actor

app_ens_activity:
    resource: "@AppBundle/Resources/config/routing/activity.yml"
    prefix:   /activity

app_ens_action_responsible:
    resource: "@AppBundle/Resources/config/routing/actionresponsible.yml"
    prefix:   /action_responsible

app_ens_action:
    resource: "@AppBundle/Resources/config/routing/action.yml"
    prefix:   /action

app_ens_scenario:
    resource: "@AppBundle/Resources/config/routing/scenario.yml"
    prefix:   /scenario